# Generated by Django 4.2.3 on 2023-07-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_logagricola_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logagricola',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logagricola',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
