# Generated by Django 4.2.3 on 2023-09-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newview_delete_mymodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newview',
            table='NewView',
        ),
    ]
