# Generated by Django 4.2.3 on 2023-09-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_newview_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewViewProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.newview',),
        ),
    ]
