# Generated by Django 4.2.3 on 2023-09-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newviewproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewViewProxy',
        ),
    ]
