# Generated by Django 4.2.3 on 2023-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_newviewproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inteiro', models.IntegerField(default=18)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='postteste',
            constraint=models.CheckConstraint(check=models.Q(('inteiro__gte', 18)), name='inteiro_gte_18'),
        ),
    ]
