# Generated by Django 4.2.3 on 2023-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postteste_postteste_inteiro_gte_18'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTeste',
        ),
        migrations.AlterModelOptions(
            name='newview',
            options={'managed': False, 'verbose_name': 'View'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
