# Generated by Django 4.2.3 on 2023-09-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_postteste_alter_newview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name_plural': 'Frotas'},
        ),
        migrations.AlterModelOptions(
            name='logagricola',
            options={'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='newview',
            options={'managed': False, 'verbose_name_plural': 'View'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name_plural': 'Operações'},
        ),
        migrations.AlterModelOptions(
            name='operationfront',
            options={'verbose_name_plural': 'Frentes por Operação'},
        ),
        migrations.AlterModelOptions(
            name='statusfleet',
            options={'verbose_name_plural': 'Status da Frota'},
        ),
        migrations.AlterModelOptions(
            name='stopgroup',
            options={'verbose_name_plural': 'Grupos de parada'},
        ),
        migrations.AlterModelOptions(
            name='stopreason',
            options={'verbose_name_plural': 'Motivos de parada'},
        ),
    ]
