# Generated by Django 4.2.3 on 2023-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_category_options_alter_fleet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterModelOptions(
            name='operationfront',
            options={'verbose_name_plural': 'Frentes'},
        ),
    ]
