# Generated by Django 4.2.3 on 2023-09-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_location_options_alter_operationfront_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newview',
            options={'managed': False, 'verbose_name_plural': 'Visualizar views'},
        ),
    ]
