# Generated by Django 4.2.3 on 2023-09-13 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_newview_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnLogFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Última info da frota',
                'db_table': 'onLogFleet',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newview',
            options={'managed': False, 'verbose_name_plural': 'Visualizar view'},
        ),
    ]
